# File Storage Application Configuration
name: file-storage
description: Python FastAPI service that provides CRUD operations for file system storage with automatic file rotation

# Docker Configuration
docker:
  build_context: .
  dockerfile: Dockerfile
  image_name: edge-terrarium-file-storage
  tag: latest

# Runtime Configuration
runtime:
  port: 9000
  health_check_path: /health
  startup_timeout: 30

# Environment Variables
environment:
  - name: SERVICE_NAME
    value: file-storage
  - name: FILE_STORAGE_HOST
    value: 0.0.0.0
  - name: FILE_STORAGE_PORT
    value: "9000"
  - name: FILE_STORAGE_PATH
    value: /app/storage
  - name: FILE_STORAGE_MAX_FILES
    value: "15"
  - name: LOGTHON_HOST
    value: logthon
  - name: LOGTHON_PORT
    value: "5000"

# Routing Configuration
routes:
  - path: /file-storage/*
    target: /
    strip_prefix: true
  - path: /storage/*
    target: /
    strip_prefix: true

# Dependencies
dependencies:
  - logthon

# Resource Requirements
resources:
  cpu:
    request: 100m
    limit: 200m
  memory:
    request: 128Mi
    limit: 256Mi

# Health Checks
health_checks:
  liveness:
    path: /health
    port: 9000
    period_seconds: 30
    timeout_seconds: 3
    failure_threshold: 3
  readiness:
    path: /health
    port: 9000
    period_seconds: 10
    timeout_seconds: 3
    failure_threshold: 3

# Volumes
volumes:
  - name: file-storage-data
    mount_path: /app/storage
    size: 1Gi
    access_mode: ReadWriteOnce

# Security Context
security:
  run_as_non_root: true
  run_as_user: 1001
  run_as_group: 1001
  allow_privilege_escalation: false
  read_only_root_filesystem: false
