# =============================================================================
# KUBERNETES CONFIGMAP - TLS CERTIFICATES TEMPLATE
# =============================================================================
# This is a template file for the Kubernetes TLS ConfigMap.
# The actual certificate data will be populated when you run the certificate generation script.
#
# Key Concepts:
# - ConfigMap: Kubernetes resource for storing configuration data
# - Data: Key-value pairs containing configuration data
# - TLS Certificates: Public certificates and private keys for HTTPS
# - Alternative to Secrets: ConfigMaps store data in plain text (not base64 encoded)
#
# This template is automatically populated by the certificate generation script
# and provides an alternative way to store TLS certificates (vs. using Secrets).
#
# Documentation: https://kubernetes.io/docs/concepts/configuration/configmap/
# =============================================================================

apiVersion: v1                    # Core API version for ConfigMap resources
kind: ConfigMap                   # Resource type - creates a configmap
metadata:                         # Metadata about this configmap
  name: edge-terrarium-tls-config # Name of the configmap
  namespace: default              # Namespace where this resource lives

# Configuration data stored in this ConfigMap
data:
  # TLS Certificate in PEM format
  # This is the public certificate that clients will use to verify the server
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIEMTCCAxmgAwIBAgIUN3zYauPFzvlFub2N0RLo+p7s7wgwDQYJKoZIhvcNAQEL
    BQAwgYAxCzAJBgNVBAYTAlVTMQswCQYDVQQIDAJDQTEWMBQGA1UEBwwNU2FuIEZy
    YW5jaXNjbzEXMBUGA1UECgwORWRnZS1UZXJyYXJpdW0xFDASBgNVBAsMC0RldmVs
    b3BtZW50MR0wGwYDVQQDDBRlZGdlLXRlcnJhcml1bS5sb2NhbDAeFw0yNTA5MDUx
    ODQ1NTNaFw0yNjA5MDUxODQ1NTNaMIGAMQswCQYDVQQGEwJVUzELMAkGA1UECAwC
    Q0ExFjAUBgNVBAcMDVNhbiBGcmFuY2lzY28xFzAVBgNVBAoMDkVkZ2UtVGVycmFy
    aXVtMRQwEgYDVQQLDAtEZXZlbG9wbWVudDEdMBsGA1UEAwwUZWRnZS10ZXJyYXJp
    dW0ubG9jYWwwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC3BwiJx9Im
    GVolhkULZZh3/ypSNKuhkxyO3QETeByXrA7GVn6dhPCVko+ENSbkA5WL8wr+FKrj
    s5I3y72do4SurxBf1pG84ZfPhCN8OiUiDFk87OUciAbbiurtGEC8hvCIKPVjfZAv
    wBLO6k9VfE03vpwzGrv5d+pPylwPGxU+xfkKieu9HbaG8yAtyhIhbUs4J/UTrIHu
    F8Djc1LVua8WAQe5gQtseKH44t70LkEOKbl4COMwGEBlrieSs20VjA4gBI7tcibu
    2flMVrtqKvw2dWVmCsHcTdWO7yA0T0onD8c+rNl+wv6wpDb94QdGHQ6RhCE+iM4f
    G2Tke2yzIZW/AgMBAAGjgaAwgZ0wCwYDVR0PBAQDAgQwMBMGA1UdJQQMMAoGCCsG
    AQUFBwMBMFoGA1UdEQRTMFGCFGVkZ2UtdGVycmFyaXVtLmxvY2Fsgglsb2NhbGhv
    c3SCFiouZWRnZS10ZXJyYXJpdW0ubG9jYWyHBH8AAAGHEAAAAAAAAAAAAAAAAAAA
    AAEwHQYDVR0OBBYEFDaeelvZ7MMuvdJmPem3IZ4MxDbFMA0GCSqGSIb3DQEBCwUA
    A4IBAQAtEIVY6aGkJ/KK5GBKf4XQURUM/GqguhYnYtX3in2iHC4YHvNzrDumoMYH
    HDiFhoInzM5gfZIe0N9ySBx7SWO6Zvhjt3pzPrtub0VYzii0n3kXdddCcbwtmYyf
    vOW8vfzgUlQ1FNeFBVdcSQlCzIhuTgkwKd2mvgRghRFfntWZYMd8k84D948AlUCw
    8q2p3KYNIw4VAD3+Ir/6dOCEt3LgNP0M6ewJIvQHCBPxEkc0nI279KNZdrNLo5ja
    eqSmXqxmRoOujlQk2Ee9exumD2OSOHitgmd/PUtQm+9fmVf0NjD+7QLpZyKfq3ZG
    xOWtKFzWJC6u/uviRWcMry87MmHn
    -----END CERTIFICATE-----
  
  # TLS Private Key in PEM format
  # This is the private key that the server uses to decrypt traffic
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC3BwiJx9ImGVol
    hkULZZh3/ypSNKuhkxyO3QETeByXrA7GVn6dhPCVko+ENSbkA5WL8wr+FKrjs5I3
    y72do4SurxBf1pG84ZfPhCN8OiUiDFk87OUciAbbiurtGEC8hvCIKPVjfZAvwBLO
    6k9VfE03vpwzGrv5d+pPylwPGxU+xfkKieu9HbaG8yAtyhIhbUs4J/UTrIHuF8Dj
    c1LVua8WAQe5gQtseKH44t70LkEOKbl4COMwGEBlrieSs20VjA4gBI7tcibu2flM
    VrtqKvw2dWVmCsHcTdWO7yA0T0onD8c+rNl+wv6wpDb94QdGHQ6RhCE+iM4fG2Tk
    e2yzIZW/AgMBAAECggEASgrZ3OdN8CTEb7bEWsp0ZmL/K3dsUXaSkIb+pvIp2v/7
    kCgwm6fKri+2yHy6KXb7ujyN32DcCza7eb/+CvY6OHLQ9Hx4w8kdoZEqy9g36nDF
    bxzEyQiMgadOx7DOi5YpW2P6dY+302FoGnX2tzYMhPci+JehoNfune3W1TOXIifC
    eNyfi8L84FPjsghLsszDabG+WkxiB3ys3N700BrfQXgLgpg8TJ+dT5BfbQgiMEDK
    jXmo+U2C0FtPklHxGm96k3mUbt3A74Ub2RGAD68ELW4es1SQAteImUDqPeUff4T7
    m5DyajzmaY+YBh6Pdoy5n8vA31FYrWBFoxozNUC+oQKBgQD9bfw2j1T8v13Y0ZpW
    PT/nzU+IDr0QvWdQLC7ctpHQ43wfsinr7pJRMzMShAtuX7rfxLfX139sjNOHVOLV
    +0o/SzcT5ltb0yY9Zfdl6mZaU3kIjioOahobpYDlw1NUmIzo2fyebAK2ZP83WC8S
    ZnBefTpPkK1eLGPbNougrK8bYQKBgQC44kDQgYTgsv6NFyNEHCNTLndOoI5SGsJF
    budTC9ySvRZD6/pp5Wa5XzyV3T8KPLxjdlt5HSQy0+7jrmlGD/uDcGUkAU7nwSAN
    5TrKTwKhAPCrD4z41q4cCU8kM3Qrn4Kt4I2CM3n6Fqm4MS1xrdMWW7zgT9Tcmlon
    /iFASCBlHwKBgFa+brW+GbjpR5YPKGScUmNlQvOvF8fDDLnEZcXmN8LoGnQ+51p6
    Llrcy35q8/6zhaNSEhsvB85/5WdNBtd3S9KeTBvjnSGxBEW/wQ6BTMdeCu+CuaJ1
    brpHy/bZBIzQKmsJMg6HqeYEa9bluDb0GUI+WtchDjZNu2AtK12zvbwBAoGAcpjb
    L+J4KIcKPQ3wcBE43CBbF0Nxs/aeIEeD3vflOpc1q9gjGWx15cTgWswOfRv0cXo1
    bLbhbxfqZPoAisrxTSFnr4+YBxKv+azyad/bc0yP4Jf8+2il9v7WLUwvX7K5X2lm
    jSO3IYrWnDLvRh1GT/+A7VDOUgbihxOALMYIPmUCgYAQLkVlCnf0zo00LcsMmkhB
    hf86ZCJ5/Y4qxU3/UONBfxQwiqAEbjHDt5V0CddwVTQq0WZuKSLh1i0KFU2S+/sl
    iHH+Mh2xgvps3h5sC1ddfsnh9Zh3aJSU3K8olfQa4y1sYYe1Fh2LsI+53AfPnaD6
    v0jeHdkPR/bRxyUkuoh6Jg==
    -----END PRIVATE KEY-----
