# Logthon Application Configuration
name: logthon
description: Python FastAPI service for log aggregation and web UI with file storage viewer

# Docker Configuration
docker:
  build_context: .
  dockerfile: Dockerfile
  image_name: edge-terrarium-logthon
  tag: latest

# Runtime Configuration
runtime:
  port: 5000
  health_check_path: /health
  startup_timeout: 30
  port_forward: 5001  # Host port for direct access

# Environment Variables
environment:
  - name: SERVICE_NAME
    value: logthon
  - name: LOGTHON_HOST
    value: 0.0.0.0
  - name: LOGTHON_PORT
    value: "5000"
  - name: LOGTHON_LOG_LEVEL
    value: INFO
  - name: FILE_STORAGE_URL
    value: http://file-storage:9000

# Routing Configuration
routes:
  - path: /logthon/*
    target: /
    strip_prefix: true
  - path: /logs/*
    target: /
    strip_prefix: true

# Dependencies
dependencies: []

# Resource Requirements
resources:
  cpu:
    request: 100m
    limit: 200m
  memory:
    request: 128Mi
    limit: 256Mi

# Health Checks
health_checks:
  liveness:
    path: /health
    port: 5000
    period_seconds: 30
    timeout_seconds: 10
    failure_threshold: 3
  readiness:
    path: /health
    port: 5000
    period_seconds: 10
    timeout_seconds: 10
    failure_threshold: 3

# Volumes (if needed)
volumes: []

# Security Context
security:
  run_as_non_root: true
  run_as_user: 1001
  run_as_group: 1001
  allow_privilege_escalation: false
  read_only_root_filesystem: false
