# Custom Client Application Configuration
name: custom-client
description: C application that handles special requests to /fake-provider/* and /example-provider/* paths

# Docker Configuration
docker:
  build_context: .
  dockerfile: Dockerfile
  image_name: edge-terrarium-custom-client
  tag: latest

# Runtime Configuration
runtime:
  port: 1337
  health_check_path: /health
  startup_timeout: 60

# Environment Variables
environment:
  - name: SERVICE_NAME
    value: custom-client
  - name: CONTAINER_NAME
    value: edge-terrarium-custom-client
  - name: VAULT_ADDR
    value: http://vault:8200
  - name: VAULT_TOKEN
    value: root
  - name: FILE_STORAGE_URL
    value: http://file-storage:9000
  - name: LOGTHON_HOST
    value: logthon
  - name: LOGTHON_PORT
    value: "5000"

# Routing Configuration
routes:
  # Host-based routing for mycoolwebsite.company.com
  # High priority routes for specific hostname
  - path: /*
    target: /
    strip_prefix: false
    host: mycoolwebsite.company.com
    priority: 200
    description: "All requests to mycoolwebsite.company.com"
  
  - path: /api/*
    target: /api/
    strip_prefix: true
    host: mycoolwebsite.company.com
    priority: 250
    description: "API endpoints for mycoolwebsite.company.com"
  
  # Default domain routing (edge-terrarium.local)
  - path: /custom-client/*
    target: /
    strip_prefix: true
    priority: 100
    description: "Custom client main endpoint"
  
  - path: /fake-provider/*
    target: /
    strip_prefix: false
    priority: 150
    description: "Fake provider endpoint"
  
  - path: /example-provider/*
    target: /
    strip_prefix: false
    priority: 150
    description: "Example provider endpoint"

# Dependencies
dependencies:
  - vault
  - logthon
  - file-storage

# Resource Requirements
resources:
  cpu:
    request: 100m
    limit: 200m
  memory:
    request: 128Mi
    limit: 256Mi

# Health Checks
health_checks:
  liveness:
    path: /health
    port: 1337
    period_seconds: 30
    timeout_seconds: 3
    failure_threshold: 3
  readiness:
    path: /health
    port: 1337
    period_seconds: 10
    timeout_seconds: 3
    failure_threshold: 3

# Volumes (if needed)
volumes: []

# Security Context
security:
  run_as_non_root: true
  run_as_user: 1001
  run_as_group: 1001
  allow_privilege_escalation: false
  read_only_root_filesystem: false
