# =============================================================================
# Custom Client Application Test Configuration
# =============================================================================
# This file defines how the custom-client application should be tested.
# Only applications with this file will be included in test runs.
#
# Format:
#   enabled: true/false - Whether to include this app in tests
#   description: Human-readable description for test output
#   routes: List of routes to test
#     - path: Route path pattern (e.g., "/app-name/*")
#       description: Optional description for the test
#       methods: List of HTTP methods to test (default: ["GET"])
#   test_config: App-specific test settings
# =============================================================================

enabled: true
description: Custom Client Service

routes:
  - path: /custom-client/*
    description: Custom Client main endpoint
    methods: ["GET"]
    query_params:
      - name: param1
        value: value1
      - name: param2
        value: value2
  - path: /fake-provider/*
    description: Fake Provider endpoint
    methods: ["GET"]
    query_params:
      - name: param1
        value: value1
      - name: param2
        value: value2
  - path: /example-provider/*
    description: Example Provider endpoint
    methods: ["GET"]
    query_params:
      - name: param1
        value: value1
      - name: param2
        value: value2

# Host-based routing test configuration
# These tests verify that requests with specific Host headers are routed correctly
host_routes:
  - host: mycoolwebsite.company.com
    path: /*
    description: "Root path for mycoolwebsite.company.com"
    methods: ["GET"]
  - host: mycoolwebsite.company.com
    path: /api/*
    description: "API endpoints for mycoolwebsite.company.com"
    methods: ["GET"]
  - host: mycoolwebsite.company.com
    path: /health
    description: "Health check for mycoolwebsite.company.com"
    methods: ["GET"]

test_config:
  # App-specific retry configuration (optional)
  # If not specified, uses global defaults
  retries: 3
  
  # App-specific timeout (optional)
  # If not specified, uses global defaults
  timeout: 10
