# =============================================================================
# TERRARIUM DOCKER COMPOSE CONFIGURATION
# =============================================================================
# This is the main Docker Compose file that orchestrates all services.
# It includes multiple compose files in the correct startup order:
#
# 1. Base services (vault, vault-init)
# 2. Core services (logthon, file-storage) 
# 3. Application services (custom-client, service-sink)
# 4. Gateway services (kong-gateway)
#
# Startup Order:
# vault → vault-init → logthon → file-storage → (custom-client, service-sink) → kong-gateway
#
# Documentation: https://docs.docker.com/compose/
# =============================================================================

# Project name - this will be used as the prefix for container names and networks
name: edge-terrarium

# Include all compose files in the correct startup order
include:
  - docker-compose.base.yml      # Base services: vault, vault-init
  - docker-compose.core.yml      # Core services: logthon, file-storage
  - docker-compose.apps.yml      # Application services: custom-client, service-sink
  - docker-compose.gateway.yml   # Gateway services: kong-gateway

# =============================================================================
# SHARED VOLUMES
# =============================================================================
# These volumes are shared across all compose files
volumes:
  custom-requests:                     # Named volume for Custom client request logs
    driver: local                   # Store on local filesystem
  vault-data:                       # Named volume for Vault data storage
    driver: local                   # Store on local filesystem
  vault-logs:                       # Named volume for Vault logs
    driver: local                   # Store on local filesystem
  file-storage-data:                # Named volume for file storage data
    driver: local                   # Store on local filesystem

# =============================================================================
# SHARED NETWORKS
# =============================================================================
# This network is shared across all compose files
networks:
  edge-terrarium-network:           # Custom network name
    driver: bridge                  # Bridge driver for container communication
    ipam:                          # IP Address Management
      config:
        - subnet: 172.25.0.0/16    # Custom subnet for container IPs