services:
  custom-client:
    build:
      context: ../../apps/custom-client
      dockerfile: Dockerfile
    image: edge-terrarium-custom-client:latest
    container_name: edge-terrarium-custom-client
    ports:
    - 1337:1337
    environment:
    - SERVICE_NAME=custom-client
    - CONTAINER_NAME=edge-terrarium-custom-client
    - VAULT_ADDR=http://vault:8200
    - VAULT_TOKEN=root
    - FILE_STORAGE_URL=http://file-storage:9000
    - LOGTHON_HOST=logthon
    - LOGTHON_PORT=5000
    networks:
    - edge-terrarium-network
    restart: unless-stopped
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://localhost:1337/health
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    depends_on:
      vault:
        condition: service_healthy
      logthon:
        condition: service_healthy
      file-storage:
        condition: service_healthy
  service-sink:
    build:
      context: ../../apps/service-sink
      dockerfile: Dockerfile
    image: edge-terrarium-service-sink:latest
    container_name: edge-terrarium-service-sink
    ports:
    - 8080:8080
    environment:
    - SERVICE_NAME=service-sink
    - CONTAINER_NAME=edge-terrarium-service-sink
    - LOGTHON_HOST=logthon
    - LOGTHON_PORT=5000
    networks:
    - edge-terrarium-network
    restart: unless-stopped
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://localhost:8080/health
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    depends_on:
      logthon:
        condition: service_healthy
