services:
  vault:
    image: hashicorp/vault:latest
    container_name: edge-terrarium-vault
    ports:
    - 8200:8200
    environment:
    - VAULT_DEV_ROOT_TOKEN_ID=root
    - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    - VAULT_ADDR=http://0.0.0.0:8200
    volumes:
    - vault-data:/vault/data
    networks:
    - edge-terrarium-network
    restart: unless-stopped
    healthcheck:
      test:
      - CMD
      - vault
      - status
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  vault-init:
    image: hashicorp/vault:latest
    container_name: edge-terrarium-vault-init
    depends_on:
      vault:
        condition: service_healthy
    volumes:
    - ./vault-init.sh:/vault-init.sh:ro
    command:
    - /bin/sh
    - /vault-init.sh
    networks:
    - edge-terrarium-network
    restart: 'no'
