services:
  nginx:
    build:
      context: ../../apps/nginx
      dockerfile: Dockerfile
    image: edge-terrarium-nginx:latest
    container_name: edge-terrarium-nginx
    ports:
    - 80:80
    environment: []
    networks:
    - edge-terrarium-network
    restart: unless-stopped
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://localhost:80/nginx-health
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    depends_on:
      custom-client:
        condition: service_healthy
      service-sink:
        condition: service_healthy
      logthon:
        condition: service_healthy
      file-storage:
        condition: service_healthy
      vault:
        condition: service_healthy
