services:
  file-storage:
    build:
      context: ../../apps/file-storage
      dockerfile: Dockerfile
    image: edge-terrarium-file-storage:latest
    container_name: edge-terrarium-file-storage
    ports:
    - 9000:9000
    environment:
    - SERVICE_NAME=file-storage
    - FILE_STORAGE_HOST=0.0.0.0
    - FILE_STORAGE_PORT=9000
    - FILE_STORAGE_PATH=/app/storage
    - FILE_STORAGE_MAX_FILES=15
    - LOGTHON_HOST=logthon
    - LOGTHON_PORT=5000
    networks:
    - edge-terrarium-network
    restart: unless-stopped
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://localhost:9000/health
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    volumes:
    - file-storage-data:/app/storage
    depends_on:
      logthon:
        condition: service_healthy
  logthon:
    build:
      context: ../../apps/logthon
      dockerfile: Dockerfile
    image: edge-terrarium-logthon:latest
    container_name: edge-terrarium-logthon
    ports:
    - 5000:5000
    environment:
    - SERVICE_NAME=logthon
    - LOGTHON_HOST=0.0.0.0
    - LOGTHON_PORT=5000
    - LOGTHON_LOG_LEVEL=INFO
    - FILE_STORAGE_URL=http://file-storage:9000
    networks:
    - edge-terrarium-network
    restart: unless-stopped
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://localhost:5000/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
