apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-client
  namespace: edge-terrarium
  labels:
    app: custom-client
    project: edge-terrarium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-client
  template:
    metadata:
      labels:
        app: custom-client
        project: edge-terrarium
    spec:
      containers:
      - name: custom-client
        
        image: edge-terrarium-custom-client:latest
        
        
        imagePullPolicy: Never
        
        
        
        ports:
        - containerPort: 1337
          name: http
        
        env:
          
          - name: SERVICE_NAME
            
            value: "custom-client"
            
          
          - name: CONTAINER_NAME
            
            value: "edge-terrarium-custom-client"
            
          
          - name: VAULT_ADDR
            
            value: "http://vault:8200"
            
          
          - name: VAULT_TOKEN
            
            value: "root"
            
          
          - name: FILE_STORAGE_URL
            
            value: "http://file-storage:9000"
            
          
          - name: LOGTHON_HOST
            
            value: "logthon"
            
          
          - name: LOGTHON_PORT
            
            value: "5000"
            
          
        
        
        
        
        
        livenessProbe:
          httpGet:
            path: /health
            port: 1337
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 3
          failureThreshold: 3
        
        
        
        readinessProbe:
          httpGet:
            path: /health
            port: 1337
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        
        
        
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
        
      