# =============================================================================
# KUBERNETES DEPLOYMENT - Custom CLIENT
# =============================================================================
# A Deployment manages a set of identical Pods (containers) and ensures they
# are running and healthy. It provides declarative updates to Pods and ReplicaSets.
#
# Key Concepts:
# - Deployment: Manages Pod replicas and rolling updates
# - Pod: The smallest deployable unit in Kubernetes (one or more containers)
# - ReplicaSet: Ensures a specified number of Pod replicas are running
# - Service: Provides network access to Pods
# - Volume: Storage that persists beyond the lifecycle of a Pod
# - Init Container: Runs before main containers start
#
# Impact:
# - Runs the Custom client application in Kubernetes
# - Waits for Vault to be ready before starting
# - Ensures secrets are available before application starts
# - Provides health checks for automatic recovery
# - Uses single replica to prevent conflicts
# - Mounts storage for request logs
#
# Documentation: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
# =============================================================================

apiVersion: apps/v1                # Apps API version for Deployment resources
kind: Deployment                   # Resource type - creates a deployment
metadata:                          # Metadata about this deployment
  name: custom-client                 # Name of the deployment
  namespace: edge-terrarium        # Namespace where this resource lives
  labels:                          # Labels for organizing resources
    app: custom-client                # Identifies this as the custom client app
    component: backend             # Identifies this as a backend component

spec:                              # Specification of the deployment
  replicas: 1                      # Number of Pod replicas to maintain (single instance for development)
  
  # Deployment strategy - use Recreate to ensure only one pod at a time
  # This prevents multiple instances from running simultaneously
  strategy:
    type: Recreate                 # Terminate old pods before creating new ones
  
  # Selector tells the deployment which Pods it manages
  selector:
    matchLabels:                   # Pods with these labels are managed by this deployment
      app: custom-client              # Must match the labels in the Pod template below

  # Template defines how new Pods should be created
  template:
    metadata:                      # Metadata for Pods created from this template
      labels:                      # Labels applied to each Pod
        app: custom-client            # Must match the selector above
        component: backend         # Identifies this as a backend component

    spec:                          # Specification for Pods created from this template
      # Init container to wait for Vault to be ready and initialized
      # Init containers run before main containers and must complete successfully
      initContainers:
      - name: wait-for-vault        # Name of the init container
        image: curlimages/curl:latest  # Lightweight curl image for health checks
        command: ['sh', '-c']       # Command to run
        args:                       # Arguments for the command
        - |                        # Multi-line script
          # Wait for Vault service to be ready
          echo "Waiting for Vault to be ready..."
          until curl -s http://vault.edge-terrarium.svc.cluster.local:8200/v1/sys/health > /dev/null; do
            echo "Vault is not ready yet. Waiting..."
            sleep 2
          done
          echo "Vault is ready! Waiting for vault-init job to complete..."
          
          # Wait for vault-init job to complete by checking if secrets are available
          # This ensures the Custom client can retrieve secrets on startup
          echo "Waiting for vault-init job to complete and secrets to be available..."
          RETRY_COUNT=0
          MAX_RETRIES=60  # 2 minutes max wait time
          until curl -s -H "X-Vault-Token: root" http://vault.edge-terrarium.svc.cluster.local:8200/v1/secret/data/custom-client/config > /dev/null; do
            RETRY_COUNT=$((RETRY_COUNT + 1))
            if [ $RETRY_COUNT -gt $MAX_RETRIES ]; then
              echo "ERROR: Timeout waiting for vault-init job to complete after $MAX_RETRIES attempts"
              echo "This indicates the vault-init job failed or is taking too long"
              exit 1
            fi
            echo "Vault-init job not complete yet (attempt $RETRY_COUNT/$MAX_RETRIES). Waiting..."
            sleep 2
          done
          echo "Vault initialization complete!"
        resources:                  # Resource requirements for init container
          requests:                 # Minimum resources required
            memory: "32Mi"          # 32 megabytes of memory
            cpu: "10m"              # 10 millicores of CPU
          limits:                   # Maximum resources allowed
            memory: "64Mi"          # 64 megabytes of memory
            cpu: "50m"              # 50 millicores of CPU
      
      containers:                  # List of containers in each Pod
      - name: custom-client           # Name of the container
        image: edge-terrarium-custom-client:latest  # Docker image to use
        imagePullPolicy: Never     # Never pull from registry (use local image for development)
        
        # Ports exposed by the container
        ports:
        - containerPort: 1337      # Port the container listens on
          name: http               # Name for referencing this port
          protocol: TCP            # Protocol (TCP or UDP)
        
        # Environment variables passed to the container
        env:
        - name: SERVICE_NAME       # Environment variable name
          value: "custom-client"      # Environment variable value
        - name: LOG_LEVEL          # Logging level
          value: "info"            # Set to info level
        - name: VAULT_ADDR         # Vault API address for Kubernetes
          value: "http://vault.edge-terrarium.svc.cluster.local:8200"
        - name: VAULT_TOKEN        # Vault authentication token
          value: "root"
        - name: LOGTHON_HOST       # Logthon service hostname for log aggregation
          value: "logthon-ingress-service.edge-terrarium.svc.cluster.local"
        - name: LOGTHON_PORT       # Logthon service port
          value: "5000"
        
        # Resource requirements and limits
        resources:
          requests:                # Minimum resources required
            memory: "64Mi"         # 64 megabytes of memory
            cpu: "50m"             # 50 millicores of CPU (0.05 cores)
          limits:                  # Maximum resources allowed
            memory: "128Mi"        # 128 megabytes of memory
            cpu: "100m"            # 100 millicores of CPU (0.1 cores)
        
        # Liveness probe - checks if container is alive
        livenessProbe:
          httpGet:                 # HTTP GET request to check health
            path: /health          # Health check endpoint
            port: 1337             # Port to check
            httpHeaders:           # Custom headers to identify probe type
            - name: X-Probe-Type
              value: "liveness"
          initialDelaySeconds: 30  # Wait 30 seconds before first check
          periodSeconds: 30        # Check every 30 seconds (industry standard)
          timeoutSeconds: 5        # Wait 5 seconds for response
          failureThreshold: 3      # Mark unhealthy after 3 failures
        
        # Readiness probe - checks if container is ready to serve traffic
        readinessProbe:
          httpGet:                 # HTTP GET request to check readiness
            path: /health          # Health check endpoint
            port: 1337             # Port to check
            httpHeaders:           # Custom headers to identify probe type
            - name: X-Probe-Type
              value: "readiness"
          initialDelaySeconds: 5   # Wait 5 seconds before first check
          periodSeconds: 10        # Check every 10 seconds (industry standard)
          timeoutSeconds: 3        # Wait 3 seconds for response
          failureThreshold: 3      # Mark not ready after 3 failures
        
        # Volume mounts - where to mount volumes in the container
        volumeMounts:
        - name: requests-storage   # Name of the volume to mount
          mountPath: /tmp/requests # Path where volume is mounted in container

      # Volumes available to containers in the Pod
      volumes:
      - name: requests-storage     # Name of the volume
        emptyDir:                  # Temporary directory that shares Pod's lifetime
          sizeLimit: 100Mi         # Maximum size of the volume

      # Restart policy for containers in the Pod
      restartPolicy: Always        # Always restart containers if they fail
