apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-storage
  namespace: edge-terrarium
  labels:
    app: file-storage
    project: edge-terrarium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-storage
  template:
    metadata:
      labels:
        app: file-storage
        project: edge-terrarium
    spec:
      containers:
      - name: file-storage
        
        image: edge-terrarium-file-storage:latest
        
        
        imagePullPolicy: Never
        
        
        
        ports:
        - containerPort: 9000
          name: http
        
        env:
          
          - name: SERVICE_NAME
            
            value: "file-storage"
            
          
          - name: FILE_STORAGE_HOST
            
            value: "0.0.0.0"
            
          
          - name: FILE_STORAGE_PORT
            
            value: "9000"
            
          
          - name: FILE_STORAGE_PATH
            
            value: "/app/storage"
            
          
          - name: FILE_STORAGE_MAX_FILES
            
            value: "15"
            
          
          - name: LOGTHON_HOST
            
            value: "logthon"
            
          
          - name: LOGTHON_PORT
            
            value: "5000"
            
          
        
        
        volumeMounts:
          
          
          - name: file-storage-data
            mountPath: /app/storage
          
        
        
        
        
        livenessProbe:
          httpGet:
            path: /health
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 3
          failureThreshold: 3
        
        
        
        readinessProbe:
          httpGet:
            path: /health
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        
        
        
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
        
      
      volumes:
        
        
        - name: file-storage-data
          persistentVolumeClaim:
            claimName: file-storage-data-pvc
        
        
      