


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-storage-data-pvc
  namespace: edge-terrarium
  labels:
    app: file-storage
    project: edge-terrarium
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


