# =============================================================================
# KUBERNETES PERSISTENT VOLUME CLAIM - FILE STORAGE
# =============================================================================
# A PersistentVolumeClaim (PVC) requests storage resources from the cluster.
# It provides persistent storage that survives pod restarts and deletions.
#
# Key Concepts:
# - PersistentVolumeClaim: Requests storage from the cluster
# - PersistentVolume: Actual storage resource in the cluster
# - Storage Class: Defines how storage is provisioned
# - Access Modes: How the volume can be accessed (ReadWriteOnce, ReadWriteMany, etc.)
# - Resources: Storage size requested
#
# Impact:
# - Provides persistent storage for file storage service
# - Ensures files survive pod restarts and deployments
# - Uses local storage for development environment
# - Supports ReadWriteOnce access mode
#
# Documentation: https://kubernetes.io/docs/concepts/storage/persistent-volumes/
# =============================================================================

apiVersion: v1                        # Core API version for PVC resources
kind: PersistentVolumeClaim           # Resource type - creates a persistent volume claim
metadata:                             # Metadata about this PVC
  name: file-storage-pvc             # Name of the PVC
  namespace: edge-terrarium          # Namespace where this resource lives
  labels:                             # Labels for organization and selection
    app: file-storage                 # Identifies this as a file storage component
    project: edge-terrarium           # Identifies this as part of the edge-terrarium project
    environment: development          # Identifies this as a development environment
    component: storage                # Identifies this as a storage component
spec:                                 # Specification for the PVC
  accessModes:                        # How the volume can be accessed
    - ReadWriteOnce                   # Can be mounted as read-write by a single node
  resources:                          # Storage resources requested
    requests:                         # Minimum storage required
      storage: 1Gi                    # Request 1 gigabyte of storage
  storageClassName: local-path        # Use local-path storage class (k3s default)
