# =============================================================================
# HTTP-ONLY INGRESS CONFIGURATION FOR K3S
# =============================================================================
# Simple HTTP-only ingress for testing without TLS complications

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: edge-terrarium-ingress-http
  namespace: edge-terrarium
  
  # Basic annotations for K3s with Kong
  annotations:
    konghq.com/strip-path: "false"
    konghq.com/preserve-host: "true"
    konghq.com/protocols: "http"

spec:
  ingressClassName: traefik
  
  # Routing rules
  rules:
  # Route /fake-provider/* and /example-provider/* to CDP Client
  - host: edge-terrarium.local
    http:
      paths:
      - path: /fake-provider
        pathType: Prefix
        backend:
          service:
            name: cdp-client-service
            port:
              number: 1337
      
      - path: /example-provider
        pathType: Prefix
        backend:
          service:
            name: cdp-client-service
            port:
              number: 1337
      
      # Route all other requests to Service Sink (default route)
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-sink-service
            port:
              number: 8080
  
  # Same routing rules for localhost
  - host: localhost
    http:
      paths:
      - path: /fake-provider
        pathType: Prefix
        backend:
          service:
            name: cdp-client-service
            port:
              number: 1337
      
      - path: /example-provider
        pathType: Prefix
        backend:
          service:
            name: cdp-client-service
            port:
              number: 1337
      
      # Route all other requests to Service Sink (default route)
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-sink-service
            port:
              number: 8080
