apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- nginx-configmap.yaml
- file-storage-deployment.yaml
- file-storage-service.yaml
- file-storage-pvc.yaml
- custom-client-deployment.yaml
- custom-client-service.yaml
- nginx-deployment.yaml
- nginx-service.yaml
- logthon-deployment.yaml
- logthon-service.yaml
- service-sink-deployment.yaml
- service-sink-service.yaml
- vault-deployment.yaml
- vault-service.yaml
- vault-pvc.yaml
- ingress.yaml
- logthon-ingress.yaml
- logthon-ingress-service.yaml
