# =============================================================================
# LOGTHON INGRESS FOR K3S
# =============================================================================
# Separate ingress configuration for Logthon with path stripping
# This allows /logs/* paths to be stripped to /* when forwarding to Logthon
#
# Key Concepts:
# - Ingress: Manages external access to services in a cluster
# - Kong Ingress Controller: Routes traffic based on host and path rules
# - Path Stripping: Removes the matched path prefix when forwarding to backend
# - TLS: Provides HTTPS encryption for secure communication
#
# Impact:
# - Routes /logs/* requests to Logthon service
# - Strips /logs prefix so /logs/health becomes /health
# - Enables SSL/TLS termination with self-signed certificates
# - Supports both edge-terrarium.local and localhost hostnames
#
# Documentation: https://kubernetes.io/docs/concepts/services-networking/ingress/
# =============================================================================

apiVersion: networking.k8s.io/v1    # Networking API version for Ingress resources
kind: Ingress                       # Resource type - creates an ingress
metadata:                           # Metadata about this ingress
  name: logthon-ingress            # Name of the ingress
  namespace: edge-terrarium        # Namespace where this resource lives
  
  # Kong-specific annotations for path stripping
  annotations:
    konghq.com/strip-path: "true"   # Strip the matched path when forwarding to backend
    konghq.com/preserve-host: "true" # Preserve the original host header
    konghq.com/protocols: "http,https"   # Allow both HTTP and HTTPS traffic

spec:                               # Specification for the ingress
  ingressClassName: kong            # Use Kong ingress controller
  
  # TLS configuration for HTTPS
  tls:                              # List of TLS configurations
  - hosts:                          # List of hostnames for this TLS configuration
    - edge-terrarium.local          # Primary hostname
    - localhost                     # Alternative hostname for local testing
    secretName: edge-terrarium-tls  # Name of the Kubernetes secret containing TLS certificates
  
  # Routing rules
  rules:                            # List of routing rules
  # Routing rules for edge-terrarium.local
  - host: edge-terrarium.local      # Hostname to match
    http:                           # HTTP routing rules
      paths:                        # List of path-based routing rules
      # Route /logs/* to Logthon with path stripping
      - path: /logs                 # Path to match
        pathType: Prefix            # Match paths that start with this prefix
        backend:                    # Backend service to route to
          service:
            name: logthon-ingress-service   # Name of the ingress-specific service
            port:
              number: 5000          # Port number on the service
  
  # Same routing rules for localhost
  - host: localhost                 # Hostname to match
    http:                           # HTTP routing rules
      paths:                        # List of path-based routing rules
      # Route /logs/* to Logthon with path stripping
      - path: /logs                 # Path to match
        pathType: Prefix            # Match paths that start with this prefix
        backend:                    # Backend service to route to
          service:
            name: logthon-ingress-service   # Name of the ingress-specific service
            port:
              number: 5000          # Port number on the service
