apiVersion: v1
kind: Service
metadata:
  name: logthon
  namespace: edge-terrarium
  labels:
    app: logthon
    project: edge-terrarium
spec:
  selector:
    app: logthon
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  type: ClusterIP