apiVersion: apps/v1
kind: Deployment
metadata:
  name: logthon
  namespace: edge-terrarium
  labels:
    app: logthon
    project: edge-terrarium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logthon
  template:
    metadata:
      labels:
        app: logthon
        project: edge-terrarium
    spec:
      containers:
      - name: logthon
        
        image: edge-terrarium-logthon:latest
        
        
        imagePullPolicy: Never
        
        
        
        ports:
        - containerPort: 5000
          name: http
        
        env:
          
          - name: SERVICE_NAME
            
            value: "logthon"
            
          
          - name: LOGTHON_HOST
            
            value: "0.0.0.0"
            
          
          - name: LOGTHON_PORT
            
            value: "5000"
            
          
          - name: LOGTHON_LOG_LEVEL
            
            value: "INFO"
            
          
          - name: FILE_STORAGE_URL
            
            value: "http://file-storage:9000"
            
          
        
        
        
        
        
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        
        
        
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
        
        
        
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
        
      