


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-config-pvc
  namespace: edge-terrarium
  labels:
    app: nginx
    project: edge-terrarium
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


