apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-sink
  namespace: edge-terrarium
  labels:
    app: service-sink
    project: edge-terrarium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-sink
  template:
    metadata:
      labels:
        app: service-sink
        project: edge-terrarium
    spec:
      containers:
      - name: service-sink
        
        image: edge-terrarium-service-sink:latest
        
        
        imagePullPolicy: Never
        
        
        
        ports:
        - containerPort: 8080
          name: http
        
        env:
          
          - name: SERVICE_NAME
            
            value: "service-sink"
            
          
          - name: CONTAINER_NAME
            
            value: "edge-terrarium-service-sink"
            
          
          - name: LOGTHON_HOST
            
            value: "logthon"
            
          
          - name: LOGTHON_PORT
            
            value: "5000"
            
          
        
        
        
        
        
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 3
          failureThreshold: 3
        
        
        
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        
        
        
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
        
      