


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-data-pvc
  namespace: edge-terrarium
  labels:
    app: vault
    project: edge-terrarium
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


