# =============================================================================
# VAULT CONFIGURATION CONFIGMAP
# =============================================================================
# This file defines the configuration for HashiCorp Vault.
# The configuration is stored in a ConfigMap so it can be easily updated
# without rebuilding the container image.
#
# Key Concepts:
# - ConfigMap: Kubernetes resource for storing configuration data
# - Vault Configuration: HCL (HashiCorp Configuration Language) format
# - Storage Backend: Where Vault stores its data (file system in this case)
# - Listener: Network configuration for Vault API
# - Development Mode: Simplified configuration for development/testing
#
# Impact:
# - Provides Vault configuration without rebuilding container images
# - Enables easy configuration updates via kubectl apply
# - Configures Vault for development mode with file storage
# - Sets up HTTP listener on port 8200 for API access
# - Enables Vault web UI for easier management
# - Configures logging to stdout for Kubernetes log collection
#
# Documentation: https://www.vaultproject.io/docs/configuration
# =============================================================================

apiVersion: v1                        # Core API version for ConfigMap resources
kind: ConfigMap                       # Resource type - creates a configmap
metadata:                             # Metadata about this configmap
  name: vault-config                  # Name of the configmap (referenced in vault-deployment.yaml)
  namespace: edge-terrarium           # Namespace where this configmap lives
  labels:                             # Labels for organization and selection
    app: vault                        # Identifies this as a Vault configuration component
    project: edge-terrarium           # Identifies this as part of the edge-terrarium project
    environment: development          # Identifies this as a development environment
data:                                 # Configuration data
  # Vault configuration file in HCL format
  # This file is mounted into the Vault container at /vault/config/vault.hcl
  vault.hcl: |
    # =============================================================================
    # VAULT CONFIGURATION FILE
    # =============================================================================
    # This is the main configuration file for HashiCorp Vault.
    # It defines how Vault should behave, where to store data, and how to listen
    # for incoming requests.
    # =============================================================================
    
    # Storage backend configuration
    # This defines where Vault stores its persistent data
    # The file backend stores data on the local filesystem
    storage "file" {
      # Path where Vault will store its data
      # This directory is mounted as a persistent volume from vault-data-pvc
      # Data stored here will persist across pod restarts
      path = "/vault/data"
    }
    
    # Listener configuration
    # This defines how Vault listens for incoming API requests
    listener "tcp" {
      # Address and port for Vault to listen on
      # 0.0.0.0 means listen on all network interfaces within the pod
      # Port 8200 is the standard Vault API port
      address = "0.0.0.0:8200"
      
      # TLS configuration (disabled for simplicity in development)
      # In production, you would enable TLS with proper certificates
      # tls_disable = false
      # tls_cert_file = "/vault/tls/vault.crt"
      # tls_key_file = "/vault/tls/vault.key"
      tls_disable = true
    }
    
    # Web UI configuration
    # This enables Vault's web interface for easier management
    # Accessible at http://vault-service:8200/ui when port-forwarded
    ui = true
    
    # API address configuration
    # This is the address that Vault will advertise to clients
    # It should be accessible from within the Kubernetes cluster
    # localhost:8200 works because it's within the same pod
    api_addr = "http://localhost:8200"
    
    # Cluster address configuration
    # This is the address for cluster-to-cluster communication
    # In a single-node setup, this is the same as api_addr
    # Port 8201 is the standard Vault cluster communication port
    cluster_addr = "http://localhost:8201"
    
    # Log level configuration
    # This controls how verbose Vault's logging is
    # Options: trace, debug, info, warn, error
    # INFO level provides good balance of detail without too much noise
    log_level = "INFO"
    
    # Log format configuration
    # This controls the format of log messages
    # Options: standard, json
    # Standard format is human-readable, json is machine-parseable
    log_format = "standard"
    
    # Log to stdout instead of file for better visibility in Kubernetes
    # This ensures logs are captured by Kubernetes and visible in kubectl logs
    # log_file = "/vault/logs/vault.log"  # Commented out to use stdout
    
    # Disable clustering for single-node setup
    # In production with multiple Vault nodes, you would enable clustering
    # Clustering provides high availability and automatic failover
    disable_clustering = true
    
    # Development mode configuration
    # This enables development mode with simplified security
    # WARNING: Never use this in production!
    # In development mode:
    # - Vault starts unsealed (no need to unseal manually)
    # - Uses in-memory storage (overridden by file storage above)
    # - Disables some security features for easier development
    # - Uses a default root token ("root")
    # For this setup, we're using file storage but keeping dev mode for simplicity
    # In production, you would disable dev mode and implement proper unsealing
