# =============================================================================
# VAULT INITIALIZATION JOB FOR K3S
# =============================================================================
# This job initializes Vault with the required secrets for K3s

apiVersion: batch/v1
kind: Job
metadata:
  name: vault-init
  namespace: edge-terrarium
  labels:
    app: vault-init
    project: edge-terrarium
    environment: development
spec:
  template:
    metadata:
      labels:
        app: vault-init
        project: edge-terrarium
        environment: development
    spec:
      restartPolicy: OnFailure
      containers:
      - name: vault-init
        image: hashicorp/vault:latest
        command: ['sh', '-c']
        args:
          - |
            export VAULT_ADDR="http://vault.edge-terrarium.svc.cluster.local:8200"
            export VAULT_TOKEN="root"
            
            echo "Waiting for Vault to be ready..."
            until vault status; do
              echo "Vault is not ready yet. Waiting..."
              sleep 2
            done
            
            echo "Vault is ready. Initializing secrets..."
            
            # Store TLS certificates (if available)
            if [ -f /tmp/certs/tls.crt ] && [ -f /tmp/certs/tls.key ]; then
              echo "Storing TLS certificates..."
              vault kv put secret/terrarium/tls \
                cert="$(cat /tmp/certs/tls.crt | base64 -w 0)" \
                key="$(cat /tmp/certs/tls.key | base64 -w 0)" \
                ca="$(cat /tmp/certs/tls.crt | base64 -w 0)"
            else
              echo "TLS certificates not found, storing mock TLS secrets..."
              vault kv put secret/terrarium/tls \
                cert="mock-cert" \
                key="mock-key" \
                ca="mock-ca"
            fi
            
            # Store CDP client configuration (matching Docker Compose)
            vault kv put secret/cdp-client/config \
              api_key="mock-api-key-12345" \
              database_url="postgresql://mock-user:mock-pass@mock-db:5432/mock-db" \
              jwt_secret="mock-jwt-secret-67890" \
              encryption_key="mock-encryption-key-abcdef" \
              log_level="INFO" \
              max_connections="100"
            
            # Store CDP client external APIs configuration
            vault kv put secret/cdp-client/external-apis \
              provider_auth_token="mock-provider-token-xyz" \
              webhook_secret="mock-webhook-secret-123" \
              rate_limit="1000" \
              timeout_seconds="30"
            
            echo "Vault initialization completed successfully!"
        
        env:
        - name: VAULT_ADDR
          value: "http://vault.edge-terrarium.svc.cluster.local:8200"
        - name: VAULT_TOKEN
          value: "root"
        
        volumeMounts:
        - name: tls-certs
          mountPath: /tmp/certs
          readOnly: true
      
      volumes:
      - name: tls-certs
        secret:
          secretName: edge-terrarium-tls
          optional: true
