# =============================================================================
# VAULT DEPLOYMENT FOR K3S
# =============================================================================
# Vault deployment for K3s with persistent storage
# Uses file storage backend for data persistence across restarts

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: edge-terrarium
  labels:
    app: vault
    project: edge-terrarium
    environment: development
spec:
  replicas: 1
  
  # Deployment strategy - use Recreate to ensure only one pod at a time
  strategy:
    type: Recreate                 # Terminate old pods before creating new ones
  
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
        project: edge-terrarium
        environment: development
    spec:
      containers:
      - name: vault
        image: hashicorp/vault:latest
        command: ["vault"]
        args: ["server", "-dev", "-dev-root-token-id=root", "-dev-listen-address=0.0.0.0:8200"]
        
        ports:
        - containerPort: 8200
          name: http
          protocol: TCP
        
        env:
        - name: VAULT_ADDR
          value: "http://0.0.0.0:8200"
        - name: VAULT_API_ADDR
          value: "http://vault.edge-terrarium.svc.cluster.local:8200"
        - name: VAULT_LOG_LEVEL
          value: "INFO"
        - name: VAULT_LOG_FORMAT
          value: "json"
        
        # volumeMounts:
        # - name: vault-config
        #   mountPath: /vault/config
        # - name: vault-data
        #   mountPath: /vault/data
        
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        
        livenessProbe:
          httpGet:
            path: /v1/sys/health
            port: 8200
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /v1/sys/health
            port: 8200
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      
      # volumes:
      # - name: vault-config
      #   configMap:
      #     name: vault-config
      # - name: vault-data
      #   persistentVolumeClaim:
      #     claimName: vault-data-pvc
