# =============================================================================
# KUBERNETES SERVICES
# =============================================================================
# A Service in Kubernetes provides a stable network endpoint for accessing
# a set of Pods. It acts as a load balancer and service discovery mechanism.
#
# Key Concepts:
# - Service: Provides stable network access to Pods
# - ClusterIP: Service type that's only accessible within the cluster
# - Selector: Defines which Pods the service routes traffic to
# - Port: External port that the service exposes
# - TargetPort: Port on the Pod that receives the traffic
#
# Documentation: https://kubernetes.io/docs/concepts/services-networking/service/
# =============================================================================

---
# ==========================================================================
# CDP CLIENT SERVICE
# ==========================================================================
# This service provides network access to the CDP client Pods.
# It routes traffic to Pods with the label "app: cdp-client"
apiVersion: v1                    # Core API version for Service resources
kind: Service                     # Resource type - creates a service
metadata:                         # Metadata about this service
  name: cdp-client-service        # Name of the service
  namespace: terrarium            # Namespace where this resource lives
  labels:                         # Labels for organizing resources
    app: cdp-client               # Identifies this service as part of the CDP client app

spec:                             # Specification of the service
  type: ClusterIP                 # Service type - only accessible within the cluster
  ports:                          # List of ports exposed by the service
  - port: 1337                    # External port that the service exposes
    targetPort: 1337              # Port on the Pod that receives the traffic
    protocol: TCP                 # Protocol (TCP or UDP)
    name: http                    # Name for referencing this port
  
  # Selector defines which Pods this service routes traffic to
  selector:
    app: cdp-client               # Routes traffic to Pods with this label

---
# ==========================================================================
# SERVICE SINK SERVICE
# ==========================================================================
# This service provides network access to the Service Sink Pods.
# It routes traffic to Pods with the label "app: service-sink"
apiVersion: v1                    # Core API version for Service resources
kind: Service                     # Resource type - creates a service
metadata:                         # Metadata about this service
  name: service-sink-service      # Name of the service
  namespace: terrarium            # Namespace where this resource lives
  labels:                         # Labels for organizing resources
    app: service-sink             # Identifies this service as part of the service-sink app

spec:                             # Specification of the service
  type: ClusterIP                 # Service type - only accessible within the cluster
  ports:                          # List of ports exposed by the service
  - port: 8080                    # External port that the service exposes
    targetPort: 8080              # Port on the Pod that receives the traffic
    protocol: TCP                 # Protocol (TCP or UDP)
    name: http                    # Name for referencing this port
  
  # Selector defines which Pods this service routes traffic to
  selector:
    app: service-sink             # Routes traffic to Pods with this label
