# Vault Secrets Configuration
# Add your secrets here - they will be automatically loaded into Vault on deployment
# Format: secret_path -> key -> value
# If its not obvious these are mock secrets and not used for any production applications

secrets:
  # Custom Client Configuration
  custom-client/config:
    api_key: "mock-api-key-12345"
    database_url: "postgresql://user:pass@db:5432/app"
    jwt_secret: "mock-jwt-secret-67890"
    encryption_key: "mock-encryption-key-abcdef"
    log_level: "INFO"
    max_connections: "100"
  
  # Custom Client External APIs
  custom-client/external-apis:
    file_storage_url: "http://file-storage:9000"
    logthon_url: "http://logthon:5000"
  
  # Terrarium TLS Configuration
  terrarium/tls:
    cert: "mock-tls-cert"
    key: "mock-tls-key"
  
  # Example: New Application Secrets
  my-app/database:
    host: "db.example.com"
    port: "5432"
    username: "myuser"
    password: "mypassword"
  
  my-app/api:
    api_key: "your-api-key-here"
    base_url: "https://api.example.com"

# Add more secrets below as needed:
# 
# Example:
# my-app/database:
#   host: "db.example.com"
#   port: "5432"
#   username: "myuser"
#   password: "mypassword"
#
# my-app/api:
#   api_key: "your-api-key-here"
#   base_url: "https://api.example.com"
